### ISSUE TITLE
plugin not working in Lysmarine SignalK

### ISSUE THREAD

**Issue by mpolazzo** [W-Geronius/signalk-hwt901b-imu#6]
Hi, I try to use the plugin with SignalK in Lysmarine OS (bareboat necessities).
Plugin configured with /dev/ttyUSB0 port.
In logfile I get this error:
Oct 14 09:21:34 2022-10-14T09:21:34.855Z signalk-hwt901b-imu plugin.stop
Oct 14 09:21:34 2022-10-14T09:21:34.861Z signalk-hwt901b-imu plugin.connect
Oct 14 09:21:34 connecting to /dev/ttyUSB0:0
Oct 14 09:21:34 2022-10-14T09:21:34.869Z signalk-hwt901b-imu Plugin options saved
Oct 14 09:21:34 POST /skServer/plugins/signalk-hwt901b-imu/config 200 9.690 ms - 50
Oct 14 09:21:34 2022-10-14T09:21:34.877Z signalk-hwt901b-imu plugin.connect.close
Oct 14 09:21:34 TypeError: DelimiterParser is not a constructor at SerialPort.<anonymous> (/home/signalk/.signalk/node_modules/.pnpm/signalk-hwt901b-imu@0.1.0/node_modules/signalk-hwt901b-imu/index.js:98:44) at SerialPort.emit (node:events:513:28) at binding.open.then.opening (/home/signalk/.signalk/node_modules/.pnpm/@serialport+stream@9.2.4/node_modules/@serialport/stream/lib/index.js:234:12)

Thanks for helping.

**Comment by mpolazzo** [comment]
It seems I have fixed my local copy by changing this row in index.js =>
`const DelimiterParser = require('@serialport/parser-delimiter')`
with the following =>
`const { DelimiterParser } = require('@serialport/parser-delimiter')`

Could you please have a look ?

**Comment by W-Geronius** [comment]
This is odd - I can't figure out, why it should not work on Lysmarine ... I haven't heard of this constraint so far.

**Comment by mpolazzo** [comment]
Sorry for answering so late. I have installed also a plugin which is derived by yours: signalk-hwt901b-imu-plus.
I get exactly the same errors as shown in my first message here. 
It is then fixed with the same fix I posted before.
I can't understand why you don't see the same issue. Have you ever tested it on a Raspberry Pi 4B with BBN os (that includes SignalK server ) ?
